autoload:
  FPDF:
    name:      FPDF
    path:      %SF_LIB_DIR%/vendor/FPDF
    recursive: true
#  Doctrine:
#    name:      Doctrine
#    path:      %SF_LIB_DIR%/vendor/Doctrine
#    recursive: true
  Swift:
    name:      Swift
    path:      %SF_LIB_DIR%/vendor/Swift/lib
    recursive: true
 
  TCPDF:
    name:      TCPDF
    path:      %SF_LIB_DIR%/vendor/tcpdf
    recursive: true
