#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 
anexoImpoTitulo: NOTAS IMPORTANTES QUE DEBEN TENER EN CUENTA EN SUS IMPORTACIONES
anexoImpo: |
  • Los fletes ofertados están basados en tarifas actuales sujetas a posibles revisiones determinadas por las compañías marítimas, aéreas o terrestres.
  • Los fletes para las importaciones aéreas se liquidaran al tipo de cambio ALAICO.
  • Los fletes para las importaciones marítimas se liquidarán a la TRM de la fecha de pago + 30 pesos colombianos, siempre y cuando esta no sea inferior a la TRM de referencia de la fecha de emisión de la factura. COLTRANS S.A., se reserva el derecho de solicitar un ajuste en caso de que la fluctuación de la moneda supere tasas impredecibles.
  • Los costos adicionales que se generen durante el manejo de la operación y que no hayan sido cotizados serán asumidos por el importador.
  • Debido a las fluctuaciones en los precios del petróleo estamos sujetos a las variaciones en el  recargo por  combustible  que determinen las aerolíneas,  las navieras  y  los  transportadores terrestres.
  • Para garantizar que la tarifa ofrecida sea aplicada correctamente por nuestro agente en el exterior, solicitamos que nos envíen la confirmación de pedido por e-mail ó fax para asegurar el seguimiento y dar información oportuna sobre sus embarques;  a  su  vez es indispensable dar instrucciones  a su  proveedor  a  favor  de  nuestro agente.
  • Favor informar a sus proveedores los perjuicios que ocasionan la información incorrecta en los documentos (volumen, número de piezas,  identificación genérica de la mercancía, etc). El importador asumirá el costo de correcciones, multas o sanciones aduaneras originadas por la información errónea dada por parte del exportador o proveedor, al igual que bodegajes y/o alquiler del contenedor causados por hechos ajenos al manejo de COLTRANS (por ejemplo: huelga, festivos, cambio de itinerarios, casos de fuerza mayor, etc).
  • Es importante que el importador nos suministre instrucciones precisas acerca de las condiciones de apilamiento, manipulación, embalaje y/o  estiba, almacenamiento y transporte de sus mercancías. Contrario, las mercancías serán manejadas bajo condiciones Standard sin asumir responsabilidad por averías, deterioros, etc.
  • Referente a la norma NIMF 15, solicitamos informar a sus proveedores en el exterior dar estricto cumplimiento a la Resolución ICA Nro. 1079, con el fin de evitar sanciones y retrasos en su operación. COLTRANS S.A. no asume ninguna responsabilidad por las consecuencias que genere el incumplimiento de dicha normatividad legal nacional e internacional.
  • En el evento que la línea naviera nos exija la firma del Contrato de Comodato, COLTRANS S.A. solicitará al cliente carta de garantía en los mismos términos establecidos por la línea aplicando un costo por el mencionado concepto. Adicionalmente, en el momento en que la naviera nos envíe las facturas originales soporte por demoras, daños, limpiezas, etc. COLTRANS S.A. procederá a facturar al cliente dichos rubros, más el cobro de un Administración.
  • Debido a las limitaciones de responsabilidad de los  transportadores y de COLTRANS S.A.,  se  exige que  el  cliente   cuente  con un seguro de  transporte.  En  caso  de  requerir  dicho  seguro se  debe  solicitar  por  escrito  su cobertura.
  • Nuestra responsabilidad contractual no excederá en ningún caso, de las limitaciones estipuladas en las normativas oficiales vigentes para el transporte marítimo, aéreo o terrestre de acuerdo con lo mencionado al dorso de los documentos de embarque correspondientes, como tampoco las limitaciones de responsabilidad estipuladas en nuestro contrato de agenciamiento.

anexoExpoTitulo: NOTAS IMPORTANTES QUE DEBEN TENER EN CUENTA EN SUS EXPORTACIONES  
anexoExpo: |
  • Los fletes ofertados están basados  en tarifas actuales sujetas  a posibles revisiones  determinadas  por las compañías marítimas,  aéreas o terrestres.
  • Los fletes para las exportaciones aéreas se liquidaran al tipo de cambio  ALAICO.
  • Los fletes para las importaciones marítimas se liquidaran a la  TRM de la  fecha  de  pago +  30  pesos colombianos,  siempre  y cuando  esta  no sea inferior  a la  TRM de  referencia de la  fecha  de  emisión de la  factura.  COLTRANS  S.A.,  se  reserva  el  derecho  de  solicitar  un  ajuste  en  caso  de  que  la  fluctuación  de  la  moneda  supere  tasas  impredecibles.
  • Las tarifas de fletes ofrecidas se deben  entender libres  de  cargue  y  descargue de las  mercancías.
  • Los  costos adicionales  que  se  generen  durante  el  manejo  de la operación y  que  no hayan sido  cotizados  serán  asumidos por el   exportador.
  • Debido a las fluctuaciones  en los precios  del  petróleo  estamos  sujetos  a las  variaciones en el  recargo por  combustible  que determinen las aerolíneas,  las navieras  y  los  transportadores terrestres.
  • La  información  errónea  por  ustedes  suministrada    en  la  factura  comercial,    lista  de  empaque  y  demás  documentos    puede  ocasionar   costos por correcciones, multas  o  sanciones  aduaneras  las  cuales  serán  cobradas   al exportador en  Colombia;  por  tal  razón,  COLTRANS   S.A.,  no  asume  responsabilidad  alguna.
  • Es importante  que  el proveedor nos  suministre  instrucciones precisas  acerca  de  las  condiciones  de  apilamiento,  manipulación,  embalaje y/o  estiba, almacenamiento y transporte de sus mercancías.   Contrario, las  mercancías serán manejadas  bajo  condiciones  estándar sin asumir  responsabilidad por  averías,  deterioros,  etc.
  • Referente  a la  norma NIMF 15,  solicitamos  dar estricto cumplimiento  a la  Resolución ICA Nro.  1079,  con  el  fin  de  evitar sanciones  y retrasos  en  su operación.  COLTRANS S.A. no asume ninguna responsabilidad por las consecuencias que  genere el incumplimiento  de  dicha  normatividad legal  nacional  e internacional.
  • Debido a las limitaciones de responsabilidad de los  transportadores y de COLTRANS S.A.,  se  exige que  el  cliente   cuente  con un seguro de  transporte.  En  caso  de  requerir  dicho  seguro se  debe  solicitar  por  escrito  su cobertura.
  • Nuestra responsabilidad contractual no excederá en ningún caso, de las limitaciones estipuladas en las normativas oficiales vigentes para el transporte marítimo, aéreo o terrestre de acuerdo con lo mencionado al dorso de los documentos de embarque correspondientes, como tampoco las limitaciones de responsabilidad estipuladas en nuestro contrato de agenciamiento.
  • En  caso  de  aceptación  de  nuestros  servicios,  estos  se  prestaran  basados  en  nuestras  condiciones  generales  de  Contrato de  Agenciamiento  de  Carga  el  cual  se  encuentra  en  la  página   WEB  www.coltrans.com.co

OTM_LCLTitulo:  NOTAS INCLUYE Y NO INCLUYE EN CONTINUACIÓN DE VIAJE (OTM/DTA) - CARGA LCL
OTM_LCL: |
  Las anteriores tarifas incluyen:
  • Formulario  DIAN para  continuación  de  viaje
  • Elaboración  OTM para continuación  de  viaje
  • Coordinación  logística
  • Tres  días libres  de bodegajes a  partir del  arribo del buque  a puerto
  • Cargue al camión en  el  terminal  marítimo
  • Transporte  terrestre  Puerto Colombiano  -  destino
  • Entrega de documentos sellados por la DIAN en destino en las  oficinas  de  Coltrans S.A.  
  
  Las anteriores tarifas no incluyen:
  • Uso de instalaciones portuarias
  • Bodegaje en puerto a  partir del cuarto día  de arribo  del buque a  puerto
  • Servicio documental  por administración de  inventario de  SPRC  USD 29
  • Inspección Aduanera
  • Movimiento Policía Fiscal
  • Seguros  a  la mercancía en el trayecto terrestre nacional
  • Reaseguro  a las mercancías para embarques cuyo monto  supere los $300.000.000
  • Servicio de Acompañamiento Vehicular o Escolta
  • Descargue en bodega de destino
  • Almacenaje en bodega de destino
  • Trámite de cesión de derechos y transporte  a zona de  destino en caso de requerir otro usuario en Zona Franca.
  • Costos adicionales que se puedan generar para el  manejo  de  mercancías  peligrosas
  
  Nota Importante: Es responsabilidad del importador, los perjuicios a que haya lugar como consecuencia de errores en la documentación suministrada, así como de las sanciones como consecuencia de requerimientos aduaneros por faltantes o sobrantes no justificados.
  
  Restricciones
  NO se pueden aceptar las siguientes cargas:
  • Menajes domésticos
  • Químicos precursores
  • Licores
  • Cigarrillos
  • Electrodomésticos
  • Adornos navideños
  Y todas aquellas  mercancías con restricciones aduaneras legales vigentes
   
  REQUISITOS PARA EL TRAMITE  DEL OTM 
  -COPIA DE LA FACTURA COMERCIAL CON TÉRMINOS DE COMPRA, PIEZAS Y PESO
  -COPIA DE LA LISTA DE EMPAQUE
  -ORIGINAL DEL HBL  
  -COPIA POLIZA DE SEGURO DE LA MERCANCIA

OTM_FCLTitulo:  NOTAS INCLUYE Y NO INCLUYE EN CONTINUACIÓN DE VIAJE (OTM/DTA) - CARGA FCL
OTM_FCL: |  
  Las anteriores tarifas incluyen:
  • Uso  de instalaciones  portuarias 
  • Tres  días libres  de  bodegajes a  partir del arribo  de  la  carga a  puerto
  • Transporte  terrestre Puerto Colombiano - Destino
  • Formulario  DIAN  para  continuación de  viaje
  • Elaboración  y  coordinación  OTM  para  continuación  de  viaje
  • Sellos para  el contendor 
  • Coordinaciòn  logística
  • Entrega de documentos sellados por la DIAN en destino en las  oficinas  de  Coltrans S.A.  
  
  Nota Importante: Es responsabilidad del importador, los perjuicios a que haya lugar como consecuencia de errores en la documentación suministrada, así como de las sanciones como consecuencia de requerimientos aduaneros por faltantes o sobrantes no justificados.
  
  Las anteriores tarifas no incluyen:
  • Servicio documental, administración de inventario de SPRC USD23,20 cartagena
  • Seguros  a  la mercancía en el trayecto terrestre nacional
  • Reaseguro  a las mercancías para embarques cuyo monto  supere los $300.000.000
  • Servicio de escolta o acompañamiento vehicular  
  • Vaciado de contenedor para inspecciòn fìsica
  • Movilización  contenedores  para  inspección física
  • Bodegaje en puerto a  partir del cuarto día  de arribo  del buque a  puerto
  • Repeso USD85
  • Firma contrato de comodato   
  • Stand by del vehículo por demoras  ajenas en el descargue
  • Almacenaje en bodega de destino    
  • Devolución de Contenedores (Drop Off) Depende de cada naviera
  • Demoras de contenedor
  • Trámites Ica, Dasalud, Invima   
  • Descargue, vaciado del contenedor en destino
  • Limpieza del contenedor
  • Descargue en bodega de destino
  • Costos adicionales que se puedan generar para el  manejo  de  mercancías  peligrosas
      
  REQUISITOS PARA EL TRAMITE  DEL OTM 
  -COPIA DE LA FACTURA COMERCIAL CON TÉRMINOS DE COMPRA, PIEZAS Y PESO
  -COPIA DE LA LISTA DE EMPAQUE
  -ORIGINAL DEL HBL
  -COPIA POLIZA DE SEGURO DE LA MERCANCIA


seguroTitulo: NOTAS DE SEGURO DE TRANSPORTE Y ADMINISTRACION DE RIESGO  
seguro: | 
  Se asegura la carga de importación, exportación, despachos nacionales o urbanos, frente a los riesgos propios del transporte de mercancías.
  1. EL VALOR ASEGURADO: deberá corresponder al valor real de la carga, es decir, su componente de costos: factura comercial, fletes internacionales, fletes nacionales, tributos aduaneros (el IVA sólo se incluye en el componente de costos cuando éste no es descontable).

  Los factores de costos diferentes a los anteriores no se deben considerar como valor asegurado, pero se pueden amparar bajo el rubro de GASTOS ADICIONALES

  2. TRAYECTO ASEGURADO: Se asegura " bodega-bodega" , es decir, desde el momento que el asegurado recibe la carga y asume la responsabilidad sobre ella, hasta su destino final en bodegas. El verdadero alcance de ese trayecto será definido por los términos de negociación INCOTERMS 2010 y el INTERÉS ASEGURABLE existente sobre la carga. Se incluyen las operaciones de cargue y descargue.

  Se excluyen destinos finales o puertos de origen de los siguientes países: Burma (Myanmar), Cuba, Irán, Irak, Liberia, Corea del Norte, Sudan, Siria, Zimbabwe, y países que eventualmente puedan ser excluidos por las leyes de los EE.UU.

  3. BIENES EXCLUIDOS: documentos o títulos valores, efectos personales o menaje doméstico, avería particular para maquinaria usada, obras de arte, semovientes, animales en general, graneles, azúcar, joyas, dinero en efectivo, monedas, valores y títulos valores, bonos cédulas hipotecarias, estampillas de timbre o correo, cartas, mapas o planos, perecederos que no cumplan con la cláusula de bienes transportados en condiciones especiales de refrigeración, congelación o calefacción.

  4. AMPAROS
      • Cobertura completa: amparo básico, falta de entrega, avería particular (se excluye para maquinaria o mercancía usada), saqueo (se
        excluye para maquinaria o mercancía usada), huelga (trayectos interiores). Incluye la cobertura de terrorismo y guerra.
      • Amparos adicionales: Lucro cesante y gastos adicionales (hasta un 10 %)
    NO ESTA AMPARADO:
      • Toma de muestras por autoridad competente, comiso, embargo, secuestro, retención,aprehensión o en general, cualquier acto
        de autoridad sobre los bienes asegurados o sobre su medio de transporte.
      • Vicio propio, combustión espontánea, merma, evaporación o filtración, no originadas en rotura o daño del empaque.
      • Pérdidas o daños causados como consecuencia de variaciones climatológicas y deterioro por el simple transcurso del tiempo.
      • Las pérdidas o daños causados por la acción de roedores, comején, gorgojo, polilla u otras plagas.
      • Fisión, fusión y, en general, cualquier reacción nuclear, emisiones ionizantes, radiación, radioactividad y contaminación radioactiva,
        sean controlada o no y sean o no, consecuencia de hechos amparados por la póliza.
      • Errores o faltas en el despacho, o pérdidas y/o daños por envío de bienes en mal estado.
      • Demoras en la entrega y pérdidas de mercado.
      • Mal empaque de las mercancías cuando el asegurado tiene el control sobre el mismo.

  5. DEDUCIBLES: No se amparan reclamaciones inferiores a $1.000.000. A partir de esta cifra los deducibles son:
      • Mercancía de alto riesgo en despachos mayores a $100.000.000 10% sobre el valor de la pérdida mínimo 3 SMMLV.
      • Otro tipo de despachos: Sin deducible

  6. MERCANCÍAS DE ALTO RIESGO: Llantas y neumáticos, algodón en pacas, productos biomédicos, teléfonos celulares o equivalentes, juegos de video, instrumentos musicales, software de videos, pieles, cigarrillos, licores, cervezas, vinos, productos farmacéuticos y veterinarios, vehículos de cualquier clase, incluyendo botes o aviones, incluyendo los movilizados por sus propios medios, repuestos automotores, Material CKD, Zinc, cobre o aluminio, perfumes, colonias y productos similares (incluyendo productos de aseo personal), Electrodomésticos, sus partes, accesorios o repuestos para los mismos, libros e impresos y textos escolares, pinturas, alimentos enlatados, leche en polvo, polipropileno, polietileno y látex en bruto o a granel, equipos de computo y/o componentes o accesorios, calzado, textiles, confecciones y cueros en productos terminados, juguetería, café y sus derivados, papel y/o productos elaborados con pulpa de papel tales como: papel higiénico, servilletas, toallas para cocina, toallas sanitarias y pañales desechables.

  7. EXCLUSIONES: Se considerarán excluidos los despachos que no cumplan las siguientes condiciones:
    A. Exclusiones por falta de acompañamiento vehicular: será obligatorio el uso de acompañantes vehiculares para los siguientes despachos dentro del territorio nacional:
      a) Mercancía de alto riesgo; despachos con un valor asegurable superior a
         $150.000.000 deberán llevar acompañamiento vehicular.
      b) Mercancía de bajo riesgo; despachos con un valor asegurable superior a
         $300.000.000 deberán llevar acompañamiento vehicular.

      La firma que se utilice para el acompañamiento deberá cumplir con los siguientes requisitos:
      • No ser personal armado.
      • Viajar en un vehículo diferente
      • Tener una central de operaciones
      • Tener acuerdos con Fuerzas Armadas
      • No hacer parte del transportador
      • Estar habilitado por la Superintendencia de Vigilancia y Seguridad Privada
    B. Empresas transportadoras: Estarán excluidos aquellos despachos que se realicen con compañías que no estén legalmente constituidas.
    C. Subrogación: estarán excluidos los despachos donde EL ASEGURADO renuncie a cualquier forma de subrogación sobre los responsables
        de un siniestro.

    Si se realizan despachos sin el cumplimiento de los anteriores requisitos, se considerará como un riesgo excluido y la Aseguradora no
    tendrá responsabilidad alguna en caso de siniestro.

  8. CLAUSULAS ADICIONALES:
      • La carga debe viajar con su valor declarado al 100% al transportista
      • Dejar en el documento de transporte constancia de la cantidad, estado y condición de los bienes a su recibo
      • No pernoctar en carreteras ni en despoblado
      • El embalaje de la mercancía debe cumplir con las normas internacionales
  
  9. SINIESTRO: debe ser reportado a seguros@coltrans.com.co a más tardar 36 Horas después de la ocurrencia del mismo.

  Para asegurar las mercancías es necesaria la instrucción por escrito.