#Recuerde identar correctamente las notas y los correspondientes espacios entre renglones 
#RECOMENDACION USE NOTEPAD++ PARA EDITAR ESTE ARCHIVO 
anexoImpoTitulo: NOTAS IMPORTANTES QUE DEBEN TENER EN CUENTA EN SUS IMPORTACIONES
anexoImpo: |
  • Los fletes ofertados están basados en tarifas actuales sujetas a posibles revisiones determinadas por las compañías marítimas, aéreas o terrestres.
  • Los fletes se liquidaran para las importaciones aéreas al tipo de cambio ALAICO y para las importaciones marítimas a la TRM de la fecha de la factura + 30 pesos colombianos. COLTRANS S.A., se reserva el derecho de solicitar un ajuste en caso de que la fluctuación de la moneda supere tasas impredecibles.
  • Los costos adicionales que se generen durante el manejo de la operación y que no hayan sido cotizados serán asumidos por el importador.
  • Debido a las fluctuaciones en los precios del petróleo estamos sujetos a las variaciones que determinen las aerolíneas y las navieras.
  • Para garantizar que la tarifa ofrecida sea aplicada correctamente por nuestro agente en el exterior, solicitamos que nos envíen la confirmación de pedido por e-mail ó fax para asegurar el seguimiento y dar información oportuna sobre sus embarques.
  • Favor informar a sus proveedores los perjuicios que ocasionan la información incorrecta en los documentos (volumen, número de piezas, identificación genérica de la mercancía, etc). El importador asumirá el costo de correcciones, multas o sanciones aduaneras originadas por la información errónea dada por parte del exportador o proveedor, al igual que bodegajes y/o alquiler del contenedor causados por hechos ajenos al manejo de COLTRANS (por ejemplo: huelga, festivos, cambio de itinerarios, casos de fuerza mayor, etc).
  • Es importante que el importador nos suministre instrucciones precisas acerca de las condiciones de apilamiento, manipulación, embalaje y/o estiba, almacenamiento y transporte de sus mercancías. Contrario, las mercancías serán manejadas bajo condiciones Standard sin asumir responsabilidad por averías, deterioros, etc.  
  • Referente a la norma NIMF 15, solicitamos informar a sus proveedores en el exterior dar estricto cumplimiento a la Resolución ICA Nro. 1079, con el fin de evitar  sanciones y retrasos en su operación.  COLTRANS S.A. no asume ninguna responsabilidad por las consecuencias que genere el incumplimiento de dicha normatividad legal nacional e internacional.
  • En el evento que la línea naviera nos exija la firma del Contrato de Comodato, COLTRANS S.A. solicitará al cliente carta de garantía en los mismos términos establecidos por la línea y aplicará un cobro de USD 20,00 por contenedor por concepto de “Firma de Contrato de Comodato”.  Adicionalmente, en el momento en que la naviera nos envíe las facturas originales soporte por demoras, daños, limpiezas, etc. COLTRANS S.A. procederá a facturar al cliente dichos rubros, más el cobro de un Administración Fee.
  • Debido a las limitaciones de nuestro Seguro de Responsabilidad Civil, aconsejamos soliciten expresamente por escrito la cobertura de un seguro de transporte.
  • Nuestra responsabilidad contractual no excederá en ningún caso, de las limitaciones estipuladas en las normativas oficiales vigentes para el transporte marítimo, aéreo o terrestre de acuerdo con lo mencionado al dorso de los documentos de embarque correspondientes, como tampoco las limitaciones de responsabilidad estipuladas en nuestro contrato de agenciamiento.
  • En caso de aceptación de nuestros servicios, estos se prestaran basados en nuestras condiciones generales de Contrato de Agenciamiento de Carga el cual se encuentra en la página WEB www.coltrans.com.co
  
  D_22_versión_03_vigencia_10-12-2007

anexoExpoTitulo: NOTAS IMPORTANTES QUE DEBEN TENER EN CUENTA EN SUS EXPORTACIONES  
anexoExpo: |
  • Los fletes ofertados están basados en tarifas actuales sujetas a posibles revisiones determinadas por las compañías marítimas, aéreas o terrestres.  
  • Los fletes se liquidaran para las exportaciones aéreas al tipo de cambio ALAICO y para las exportaciones marítimas a la TRM de la fecha de la factura + 30 pesos colombianos. COLTRANS S.A., se reserva el derecho de solicitar un ajuste en caso de que la fluctuación de la moneda supere tasas impredecibles.  
  • Las tarifas de fletes ofrecidas se deben entender libres de cargue y descargue de las mercancías  
  • Los costos adicionales que se generen durante el manejo de la operación y que no hayan sido cotizados serán asumidos por el exportador.
  • Debido a las fluctuaciones en los precios del petróleo estamos sujetos a las variaciones que determinen las aerolíneas y las navieras.
  • La información errónea por ustedes suministrada en la factura comercial, lista de empaque y demás documentos puede ocasionar costos por correcciones, multas o sanciones aduaneras las cuales serán cobradas al exportador en Colombia o al importador; por tal razón, COLTRANS S.A., no asume responsabilidad alguna.
  • Es importante que el exportador nos suministre instrucciones precisas acerca de las condiciones de apilamiento, manipulación, embalaje y/o estiba, almacenamiento y transporte de sus mercancías.  Contrario, las mercancías serán manejadas bajo condiciones estándar sin asumir responsabilidad por averías, deterioros, etc.
  • Referente a la norma NIMF 15 , solicitamos dar estricto cumplimiento a la Resolución ICA Nro. 1079, con el fin de evitar sanciones y retrasos en su operación.  COLTRANS S.A. no asume ninguna responsabilidad por las consecuencias que genere el incumplimiento de dicha normatividad legal nacional  e internacional.
  • Debido a las limitaciones de nuestro Seguro de Responsabilidad Civil, aconsejamos soliciten expresamente por escrito la cobertura de un seguro de transporte.
  • Nuestra responsabilidad contractual no excederá en ningún caso, de las limitaciones estipuladas en las normativas oficiales vigentes para el transporte marítimo, aéreo o terrestre de acuerdo con lo mencionado al dorso de los documentos de embarque correspondientes, como tampoco las limitaciones de responsabilidad estipuladas en nuestro contrato de agenciamiento.
  • En caso de aceptación de nuestros servicios, estos se prestaran basados en nuestras condiciones generales de Contrato de Agenciamiento de Carga el cual se encuentra en la página WEB www.coltrans.com.co
  
  D_21_versión_3_vigencia_10-12-2007
  
OTM_LCLTitulo:  NOTAS INCLUYE Y NO INCLUYE EN CONTINUACIÓN DE VIAJE (OTM/DTA) - CARGA LCL
OTM_LCL: |
  Las anteriores tarifas incluyen:
  * Formulario  DIAN para  continuación  de  viaje
  * Elaboración  OTM para continuación  de  viaje
  * Coordinación  logística
  * Tres  días libres  de bodegajes a  partir del  arribo del buque  a puerto
  * Cargue al camión en  el  terminal  marítimo
  * Transporte  terrestre  Puerto Colombiano  -  destino
  * Entrega de documentos sellados por la DIAN en destino en las  oficinas  de  Coltrans S.A.  Bogotá
  
  Las anteriores tarifas no incluyen:
  * Uso de instalaciones portuarias
  * Bodegaje en puerto a  partir del cuarto día  de arribo  del buque a  puerto
  * Servicio documental  por administración de  inventario de  SPRC  USD 23,20
  * Inspección Aduanera
  * Movimiento Policía Fiscal
  * Seguros  a  la mercancía en el trayecto terrestre nacional
  * Reaseguro  a las mercancías para embarques cuyo monto  supere los $300.000.000
  * Servicio de Acompañamiento Vehicular o Escolta
  * Descargue en bodega de destino
  * Almacenaje en bodega de destino
  * Trámite de cesión de derechos y transporte  a zona de  destino en caso de requerir otro usuario en Zona Franca.
  * Costos adicionales que se puedan generar para el  manejo  de  mercancías  peligrosas
  
  Restricciones
  NO se pueden aceptar las siguientes cargas:
  * Menajes domésticos
  * Químicos precursores
  * Licores
  * Cigarrillos
  * Electrodomésticos
  * Adornos navideños
  Y todas aquellas  mercancías con restricciones aduaneras legales vigentes
  
  Para  realizar  el  OTM   se  requiere:
  » CARTAGENA «
  No se necesita consignar el Bl Master al OPERADOR MULTIMODAL
  DEBE venir consignado el  HBL con las anteriores indicaciones
   COPIA DE LA FACTURA COMERCIAL CON TERMINOS DE COMPRA,PIEZAS Y PESO
  - ORIGINAL DEL HBL 
  La carga debe venir asegurada
  
  » BUENAVENTURA «
  Debe venir consignado el Bl Master a nombre del OPERADOR MULTIMODAL, consignado así:
  Operador Multimodal / Nombre Zona aduanera y/o   Z . Franca /
  
  REQUISITOS PARA EL TRAMITE  DEL OTM 
  -COPIA DE LA FACTURA COMERCIAL CON TÉRMINOS DE COMPRA, PIEZAS Y PESO
  -COPIA DE LA LISTA DE EMPAQUE
  -ORIGINAL DEL HBL  

OTM_FCLTitulo:  NOTAS INCLUYE Y NO INCLUYE EN CONTINUACIÓN DE VIAJE (OTM/DTA) - CARGA FCL
OTM_FCL: |  
  Las anteriores tarifas incluyen:
  • Uso  de instalaciones  portuarias 
  • Tres  días libres  de  bodegajes a  partir del arribo  de  la  carga a  puerto
  • Transporte  terrestre
  • Formulario  DIAN  para  continuación de  viaje
  • Elaboración  y  coordinación  OTM  para  continuación  de  viaje
  • Sellos para  el contendor 
  • Cierre de  la  continuación  de viaje en destino 
  • Coordinaciòn  logística
  
  Las anteriores tarifas no incluyen:
  • Servicio documental, administración de inventario de SPRC USD20 cartagena
  • Seguros a la carga
  • Servicio de escolta o acompañamiento vehicular
  • Stand by del vehículo por demoras  ajenas en el descargue
  • Vaciado de contenedor para inspecciòn fìsica
  • Movilización  contenedores  para  inspección física
  • Bodegajes en puerto a partir del tercer dìa de arribo de la mercancía a puerto
  • Repeso USD65
  • Almacenajes
  • Firma contrato de comodato 
  • Vaciado de contenedor
  • Devolución de Contenedores (Drop Off) Depende de cada naviera
  • Demoras de contenedor
  • Trámites Ica, Dasalud, Invima 
  • Descargue, vaciado del contenedor en destino
  • Limpieza del contenedor
  
  Para  realizar  el  OTM   se  requiere:
    » CARTAGENA «
  No se necesita consignar el Bl Master al OPERADOR MULTIMODAL
  DEBE venir consignado el  HBL con las anteriores indicaciones
     COPIA DE LA FACTURA COMERCIAL CON TERMINOS DE COMPRA,PIEZAS Y PESO
  - ORIGINAL DEL HBL 
  La carga debe venir asegurada
  
    » BUENAVENTURA «
  Debe venir consignado el Bl Master a nombre del OPERADOR MULTIMODAL, consignado así:
  Operador Multimodal / Nombre Zona aduanera y/o   Z . Franca /
  
  REQUISITOS PARA EL TRAMITE  DEL OTM 
  -COPIA DE LA FACTURA COMERCIAL CON TÉRMINOS DE COMPRA, PIEZAS Y PESO
  -COPIA DE LA LISTA DE EMPAQUE
  -ORIGINAL DEL HBL

seguroTitulo: NOTAS DE SEGURO DE TRANSPORTE Y ADMINISTRACION DE RIESGO  
seguro: | 
  EL VALOR ASEGURADO: deberá corresponder al valor real de la carga, es decir, su componente de costos: factura comercial, fletes internacionales, fletes nacionales, tributos aduaneros (el  IVA sólamente se incluye en el componente de costos cuando éste no es deducible).
  
  Los factores de costos diferentes a los anteriores no se deben considerar como valor asegurado, pero se pueden asegurar bajo el rubro de GASTOS ADICIONALES
 
  TRAYECTO ASEGURADO: Se asegura "bodega-bodega", es decir, desde el momento que el Asegurado recibe la carga y asume la responsabilidad sobre ella, hasta su destino final en bodegas. El verdadero alcance de ese trayecto será definido por los términos de negociación INCOTERMS 2000 y el INTERÉS ASEGURABLE existente sobre la carga. Se incluyen las operaciones de cargue y descargue.
  
  Se excluyen destinos finales o puertos de origen los siguientes países: Burma (Myanmar), Cuba, Irán, Irak, Liberia, Corea del Norte, Sudan, Siria, Zimbabwe, y países que eventualmente puedan ser excluidos por las leyes de los EE.UU.)
   
  BIENES ASEGURADOS: se asegura todo tipo de carga excluyendo la siguiente:
  • Documentos o títulos valores
  • Efectos personales o menaje doméstico 
  • Avería particular para maquinaria usada
  • Obras de arte
  • Semovientes, animales en general.
  • Graneles
  • Azúcar
  • Joyas, dinero en efectivo, monedas, valores y títulos valores, bonos cédulas hipotecarias, estampillas de timbre o correo, cartas, mapas o planos.
  • Perecederos que no cumplan con la cláusula de bienes transportados en condiciones especiales de refrigeración, congelación o calefacción.
  
  AMPAROS
  • Cobertura completa
  • Amparo básico
  • Falta de entrega
  • Avería particular
  • Saqueo
  • Huelga (trayectos interiores) Incluye la cobertura de terrorismo.
  • Guerra
  • Amparos adicionales
  • Lucro cesante (hasta un 10 % y opcional)
  • Gastos adicionales (hasta un 10 % y opcional)
  
  Nota: Se aclara que no se asegura la AVERÍA PARTICULAR para mercancías y maquinaria usada excluyéndose el daño eléctrico o mecánico interno.
   
  NO ESTA AMPARADO: 
  • Toma de muestras por autoridad competente, comiso, embargo, secuestro, retención, aprehensión o en general, cualquier acto de autoridad sobre los bienes asegurados o sobre su medio de transporte.
  • Vicio propio, combustión espontánea, merma, evaporación o filtración, no originadas en rotura o daño del empaque.
  • Pérdidas o daños causados como consecuencia de variaciones climatológicas y deterioro por el simple transcurso del tiempo.
  • Las pérdidas o daños causados por la acción de roedores, comején, gorgojo, polilla u otras plagas.
  • Fisión, fusión y, en general, cualquier reacción nuclear, emisiones ionizantes, radiación, radioactividad y contaminación radioactiva, sean controlada o no y sean o no, consecuencia de hechos amparados por la póliza.
  • Errores o faltas en el despacho, o pérdidas y/o daños por envío de bienes en mal estado.
  • Demoras en la entrega y pérdidas de mercado.
  • Mal empaque de las mercancías cuando el asegurado tiene el control sobre el mismo. 
  
  DEDUCIBLES: No se amparan reclamaciones menores a $1.000.000. A partir de esta cifra los deducibles son:
  Mercancía de alto riesgo en despachos mayores a $100.000.000 10% sobre el valor de la pérdida mínimo 3 SMMLV.
  Otro tipo de despachos:  Sin deducible
   
  MERCANCÍAS DE ALTO RIESGO
  • Llantas y neumáticos
  • Algodón en pacas
  • Productos biomédicos
  • Teléfonos Celulares o equivalentes, Juegos de video, software de videos
  • Pieles
  • Cigarrillos, Licores, cervezas, vinos.
  • Productos Farmacéuticos y Veterinarios
  • Vehículos de cualquier clase, incluyendo botes o aviones, incluyendo los movilizados por sus propios medios.
  • Repuestos Automotores, Material CKD.
  • Zinc, Cobre o Aluminio.
  • Perfumes, colonias y productos similares (incluyendo productos de aseo personal)
  • Electrodomésticos, sus partes, accesorios o repuestos para los mismos.
  • Libros e impresos y textos escolares.
  • Pinturas.
  • Alimentos Enlatados, Leche en Polvo
  • Polipropileno, polietileno y látex en bruto o a granel.
  • Equipos de Computo y/o Componentes o Accesorios.
  • Calzado, Textiles, Confecciones y Cueros en productos terminados.
  • Juguetería.
  • Café y sus derivados
  • Papel y/o productos elaborados con pulpa de papel tales como: papel higiénico, servilletas, toallas para cocina, tollas sanitarias y pañales desechables.
  
  EXCLUSIONES: Se considerará excluidos los despachos que no cumplan las siguientes condiciones. Si se realizan despachos sin el cumplimiento de los requisitos exigidos, se considerará como un riesgo excluido del presente contrato y la Aseguradora no tendrá responsabilidad alguna en caso de siniestro:
  
  1) Exclusiones por falta de acompañamiento vehicular: será obligatorio el uso de acompañantes vehiculares para los siguientes despachos dentro del territorio nacional:
    a) Mercancía de alto riesgo: despachos con un valor asegurable superior a $150.000.000 deberán llevar acompañamiento vehicular.
    b) Mercancía de bajo riesgo: despachos con un valor asegurable superior a $300.000.000 deberán llevar acompañamiento vehicular.
  2) Empresas transportadoras: Estarán excluidos aquellos despachos que se realicen con compañías que no estén legalmente constituidas. 
  3) Subrogación: estarán excluidos los despachos donde EL ASEGURADO renuncie a cualquier forma de subrogación sobre los responsables de un siniestro. 
  
  EN CASO DE SINIESTRO: debe ser reportado a seguros@coltrans.com.co a más tardar 36 Hrs después de la ocurrencia del mismo.